# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actionlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatetime', models.DateTimeField(blank=True, db_column='operateTime', null=True)),
                ('logevent', models.CharField(blank=True, max_length=100, null=True)),
                ('userid', models.IntegerField(blank=True, db_column='userID', null=True)),
                ('loglevel', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outerip', models.CharField(blank=True, db_column='outerIP', max_length=50, null=True)),
                ('outerport', models.IntegerField(blank=True, db_column='outerPort', null=True)),
                ('innerip', models.CharField(blank=True, db_column='innerIP', max_length=50, null=True)),
                ('innerport', models.IntegerField(blank=True, db_column='innerPort', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientterminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerid', models.CharField(db_column='RegisterID', max_length=45)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('clienttype', models.IntegerField(blank=True, db_column='clientType', null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IcbcDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbip', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipid', models.CharField(blank=True, db_column='sipID', max_length=45, null=True)),
                ('remoteip', models.CharField(blank=True, db_column='remoteIP', max_length=45, null=True)),
                ('remoteport', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('serverid', models.AutoField(primary_key=True, serialize=False)),
                ('servername', models.CharField(blank=True, max_length=45, null=True)),
                ('serverip', models.CharField(blank=True, max_length=45, null=True)),
                ('serverport', models.IntegerField(blank=True, null=True)),
                ('sipport', models.IntegerField(blank=True, db_column='sipPort', null=True)),
                ('devicelimitecode', models.CharField(blank=True, max_length=50, null=True)),
                ('devicelimite', models.IntegerField(blank=True, null=True)),
                ('servermask', models.CharField(blank=True, max_length=45, null=True)),
                ('gateway', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('usertype', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XtWatvediochannelinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipid', models.CharField(db_column='sipID', max_length=45)),
                ('devicename', models.CharField(blank=True, max_length=45, null=True)),
                ('deviceip', models.CharField(blank=True, max_length=45, null=True)),
                ('tcpport', models.IntegerField(blank=True, null=True)),
                ('devicetype', models.IntegerField(blank=True, null=True)),
                ('streamtransmode', models.IntegerField(blank=True, null=True)),
                ('rasuser', models.CharField(blank=True, max_length=45, null=True)),
                ('raspassword', models.CharField(blank=True, max_length=45, null=True)),
                ('groupid', models.IntegerField(blank=True, null=True)),
                ('channelid', models.IntegerField(blank=True, null=True)),
                ('devicechannelindex', models.IntegerField(blank=True, null=True)),
                ('streamserverip', models.CharField(blank=True, max_length=45, null=True)),
                ('streamtcpport', models.IntegerField(blank=True, null=True)),
                ('nlcserverport', models.IntegerField(blank=True, null=True)),
                ('nlcclientport', models.IntegerField(blank=True, null=True)),
                ('streamusername', models.CharField(blank=True, max_length=45, null=True)),
                ('streamuserpws', models.CharField(blank=True, max_length=45, null=True)),
                ('deptname', models.CharField(blank=True, max_length=45, null=True)),
                ('groupname', models.CharField(blank=True, max_length=45, null=True)),
                ('ename', models.CharField(blank=True, max_length=45, null=True)),
                ('channelname', models.CharField(blank=True, max_length=45, null=True)),
                ('usemediaserver', models.IntegerField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('terminalid', models.IntegerField(blank=True, null=True)),
                ('districtcode', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='addressmapping',
            unique_together=set([('outerip', 'innerip')]),
        ),
    ]
