# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmapping',
            name='innerip',
            field=models.CharField(blank=True, db_column='innerIP', max_length=50, null=True, verbose_name='\u5185\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='addressmapping',
            name='outerip',
            field=models.CharField(blank=True, db_column='outerIP', max_length=50, null=True, verbose_name='\u5916\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='xtwatvediochannelinfo',
            name='channelid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
