# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20170710_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientterminal',
            name='location',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
