# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20170717_0822'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actionlog',
            table='actionlog',
        ),
        migrations.AlterModelTable(
            name='addressmapping',
            table='addressmapping',
        ),
        migrations.AlterModelTable(
            name='clientterminal',
            table='clientterminal',
        ),
        migrations.AlterModelTable(
            name='icbcdb',
            table='icbcdb',
        ),
        migrations.AlterModelTable(
            name='monitoring',
            table='monitoring',
        ),
        migrations.AlterModelTable(
            name='server',
            table='server',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.AlterModelTable(
            name='xtwatvediochannelinfo',
            table='xtWatvediochannelinfo',
        ),
    ]
