# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20170717_1124'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressmapping',
            table='address_mapping',
        ),
    ]
