# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20170717_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='icbcdb',
            name='dbname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='icbcdb',
            name='districtcode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
