# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20170718_0838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xtwatvediochannelinfo',
            table='xt_watvediochannelinfo',
        ),
    ]
