# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_sipinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipinfo',
            name='typeCode',
            field=models.CharField(default='131', max_length=3, verbose_name='\u7c7b\u578b\u7f16\u7801'),
        ),
        migrations.AlterField(
            model_name='sipinfo',
            name='industryCode',
            field=models.CharField(max_length=2, verbose_name='\u884c\u4e1a\u7f16\u7801'),
        ),
    ]
