# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-01 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20170810_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='operatetime',
            field=models.DateTimeField(auto_now=True, db_column='operateTime', null=True),
        ),
    ]
