# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20170901_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='downloadauthority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='playbackauthority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
