# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20171220_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='downloadauthority',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u4e0b\u8f7d\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='server',
            name='playbackauthority',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u56de\u653e\u6743\u9650'),
        ),
    ]
